# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[4.46586735e-01 7.12794646e-02 4.09891644e-01]
  [9.59594873e-01 9.41186923e-01 2.99305553e-01]
  [1.88722444e-01 7.92163839e-01 8.87468523e-02]]

 [[6.69121185e-01 2.34437491e-01 7.42166749e-01]
  [1.86956458e-01 9.69255150e-01 3.31185187e-01]
  [8.73665862e-02 7.71962009e-01 1.92653372e-01]]

 [[1.88899256e-01 4.12142655e-02 7.57300412e-01]
  [2.77528616e-01 6.05747303e-01 9.05506539e-01]
  [7.33626600e-01 4.97222355e-01 2.77947265e-04]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
import numpy as np
arr = np.diag([1, 2, 3, 4, 5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [14]:
import numpy as np
arr = np.ones((3,3))
arr = np.zeros((8,8),dtype=int)

arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [19]:
import numpy as np
arr= np.random.random((5,5))
print("Original Array:")
print(x)
arrmax =  arr.max()
arrmin = arr.min()
Arr= (arr - arrmin)/(arrmax - arrmin)
print("After normalization:")
print(Arr)

Original Array:
[[0.07125924 0.83767887 0.56951106 0.11984415 0.3435927 ]
 [0.44442469 0.35624532 0.18997658 1.         0.12620234]
 [0.54353954 0.         0.78162325 0.41825797 0.17685049]
 [0.93448489 0.53479354 0.48640067 0.4346577  0.36269335]
 [0.90832237 0.18740974 0.57219485 0.80507546 0.83923247]]
After normalization:
[[0.5343851  0.5746208  0.         0.82050117 1.        ]
 [0.22591725 0.08993571 0.24254276 0.57998508 0.19235348]
 [0.89068514 0.92750854 0.96145346 0.16551826 0.06719803]
 [0.25627748 0.280358   0.89549376 0.61870299 0.08464572]
 [0.32707313 0.3236299  0.0906765  0.09349342 0.10501775]]


# 5.  How to find common values between two arrays?

In [20]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [22]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [24]:
import numpy as np
arr = np.random.randint(0,2,6)
print("First array:")
print(arr)
arr1 = np.random.randint(0,2,6)
print("Second array:")
print(arr1)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(arr, arr1)
print(array_equal)

First array:
[0 0 1 1 1 0]
Second array:
[0 1 0 1 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [25]:
import numpy as np
arr = np.random.random(10)
print("Original array:")
print(arr)
arr[arr.argmax()] = -1
print("Maximum value replaced by -1:")
print(arr)

Original array:
[0.28798284 0.92962683 0.35001511 0.18439987 0.88995877 0.30124903
 0.67047484 0.25984495 0.89833223 0.31863168]
Maximum value replaced by -1:
[ 0.28798284 -1.          0.35001511  0.18439987  0.88995877  0.30124903
  0.67047484  0.25984495  0.89833223  0.31863168]


# 9. How to print all the values of an array?

In [39]:
import numpy as np
np.set_printoptions(threshold=30)
arr = np.zeros((4, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [28]:
import numpy as np
print("Original matrix:\n")
arr = np.random.rand(5, 10)
print(arr)
print("\nSubtract the mean of each row of the said matrix:\n")
arr1 = arr - arr.mean(axis=1, keepdims=True)
print(arr1)

Original matrix:

[[0.02049841 0.07375614 0.26369683 0.16364753 0.74857877 0.02557691
  0.72904708 0.04919231 0.72161079 0.59171976]
 [0.31098328 0.70414082 0.60142444 0.12408978 0.18291109 0.17231686
  0.30873313 0.43134851 0.90742826 0.37461794]
 [0.92372237 0.05969985 0.68783373 0.88474657 0.02370802 0.52872117
  0.72501094 0.89840337 0.31844727 0.23273522]
 [0.5293941  0.93803493 0.7936058  0.63817082 0.76702019 0.57612596
  0.79213942 0.96636712 0.34858873 0.73935193]
 [0.47167975 0.01984977 0.61916425 0.44212524 0.2339474  0.26196768
  0.99339715 0.60952468 0.23589263 0.3344481 ]]

Subtract the mean of each row of the said matrix:

[[-3.18234042e-01 -2.64976314e-01 -7.50356207e-02 -1.75084927e-01
   4.09846313e-01 -3.13155544e-01  3.90314631e-01 -2.89540139e-01
   3.82878339e-01  2.52987304e-01]
 [-1.00816131e-01  2.92341408e-01  1.89625028e-01 -2.87709628e-01
  -2.28888318e-01 -2.39482555e-01 -1.03066279e-01  1.95490958e-02
   4.95628849e-01 -3.71814704e-02]
 [ 3.95419517e-01 -4

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [34]:
import numpy as np
arr = np.ones(10)
arr1 = np.random.randint(0,len(arr),20)
arr += np.bincount(arr1, minlength=len(arr))
print(arr)

[3. 3. 2. 2. 2. 3. 4. 3. 4. 4.]


# 12.How to get the diagonal of a dot product?

In [35]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([73,  3, 74])

# 13.How to find the most frequent value in an array?

In [33]:
import numpy as np
arr = np.random.randint(0, 10, 40)
print("Original array:")
print(arr)
print("Most frequent value in the above array:")
print(np.bincount(arr).argmax())

Original array:
[1 5 9 4 7 2 3 6 2 6 0 7 8 0 8 5 2 0 8 1 1 1 5 3 7 5 4 7 8 4 0 0 9 1 6 9 8
 3 0 7]
Most frequent value in the above array:
0


# 14.How to get the n largest values of an array

In [32]:
import numpy as np
arr = np.arange(10)
print("Original array:")
print(arr)
np.random.shuffle(arr)
n = 1
print (arr[np.argsort(arr)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [31]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array(['Red','Green','White','Orange'])
arr3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([arr1, arr2, arr3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
